services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./UserFlow:/app
      - /app/node_modules # Evita sobrescrever node_modules do container com o do host
    working_dir: /app
    environment:
      - NODE_ENV=test
    # Usa ng test para aproveitar a configuração do Angular CLI e do Vitest
    command: /bin/sh -c "npm install && npx ng test --watch=false --browsers=chromium --headless"
