name: Angular Unit Tests (Vitest)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./UserFlow

    steps:
    - name: Fazer o Checkout do código
      uses: actions/checkout@v6

    - name: Preparar ambiente Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '22' 
        cache: 'npm' 
        cache-dependency-path: './UserFlow/package-lock.json'

    - name: Instalar dependências
      run: npm ci

    - name: Executar testes do Vitest
      run: npm run test
